### PR TITLE
Add logos and banner to 'graphics' folder and insert banner into READ…

### PR DESCRIPTION
**Pull request by RechieKho**
…ME.md

*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:
- Logos, a banner, Inkscape's `.svg` file, and a README.md file is added in the `graphics` folder. 
- The banner is inserted into the README.md (NOT THE README.md IN `graphics` FOLDER).
- Logos with different dimensions in `.png` format are stored in `graphics/logos` folder.
- The README.md file in the `graphics` folder contains a description of the logos and the banner.
- There is all `dark` version of the logos and banner named with suffix `_dark`. 
- View the logos and banner at [here](https://github.com/RechieKho/Peregrine/tree/main/graphics)

Explain the **details** for making this change. What existing problem does the pull request solve?
- Where is the logo?

**Code formatting**

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by SaptakBhoumik** [comment]
@RechieKho This is not our logo

**Comment by SaptakBhoumik** [comment]
@RechieKho Use this logo

**Comment by RechieKho** [comment]
I'm ok with redrawing logo, but isn't it weird that the name of the
language is peregrine but the logo implies a swallow?

**Comment by SaptakBhoumik** [comment]
Both of them are birds @RechieKho

**Comment by RechieKho** [comment]
ok...

**Comment by SaptakBhoumik** [comment]
@RechieKho please change the logo

**Comment by RechieKho** [comment]
I hope this satisfies you.

**Comment by SaptakBhoumik** [comment]
@RechieKho  There is a typo in the logo. Can you fix it and create a new pull request

**Comment by SaptakBhoumik** [comment]
It is Peregrine

**Pull request merged**
