### PR TITLE
Refined argument parser

### PR DESCRIPTION
**Pull request by pranavbaburaj**
*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*

Please provide enough information so that others can review your pull request:
I made some changed to the argument parser. Now, it will be easy to expand the cli with more commands. But, I have changed how the arguments are parsed in the cli. An example 👇
```sh
swallow compile <filename> --o=<output-file>
```

Explain the **details** for making this change. What existing problem does the pull request solve?
The pull request cleans up the mess in the main function and allows the cli to expand with more commands

**Code formatting**
The V code was formatted with `v fmt`. The C code was beautified with `clang_format`

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if such).

### CODE REVIEW

**Comment by pranavbaburaj** [comment]
Another thing to be noted. I experienced a few errors while running the program. The error said that, function `inputString` was not defined. I think its some issue with the builtin library.  Please look into the issue.

**Comment by pranavbaburaj** [comment]
The argument parser can be expanded as shown in the example below 👇

```v
fn execute(results ArgumentParserOptions) {
	if results.is_help || results.error {
		print_help()
		return
	}
	if results.command == 'compile' {
		// ...
	} else if result.command == 'fmt' {
	        // code
        }
}
```

**Comment by SaptakBhoumik** [comment]
I will merge it after reviewing the code @pranavbaburaj

**Comment by pranavbaburaj** [comment]
> I will merge it after reviewing the code @pranavbaburaj

Ah ok. thanks :)

**Comment by SaptakBhoumik** [comment]
> Another thing to be noted. I experienced a few errors while running the program. The error said that, function `inputString` was not defined. I think its some issue with the builtin library. Please look into the issue.

Can you tell me which version of V are you using

**Comment by SaptakBhoumik** [comment]
@pranavbaburaj Thank you for your contribution

**Comment by pranavbaburaj** [comment]
Thank you for merging the pull request :)

**Comment by pranavbaburaj** [comment]
> > Another thing to be noted. I experienced a few errors while running the program. The error said that, function `inputString` was not defined. I think its some issue with the builtin library. Please look into the issue.
> 
> Can you tell me which version of V are you using(create a new issue because windows user are facing it for some reason)

I downloaded the latest release from the weekly releases.
```
V 0.2.4 24c1d55
```

**Comment by pranavbaburaj** [comment]
Just a doubt. when I look at the main branch, I don't see any changes with the main function 🤔

**Comment by SaptakBhoumik** [comment]
> Just a doubt. when I look at the main branch, I don't see any changes with the main function thinking

Well unfortunately your code had a bug so I had to revert some changes

**Comment by pranavbaburaj** [comment]
ah. thats unfortunate. Would like to know what went wrong!

**Comment by SaptakBhoumik** [comment]
> ah. thats unfortunate. Would like to know what went wrong!

The CLI and builtin.h was kind of broken

**Comment by SaptakBhoumik** [comment]
> Another thing to be noted. I experienced a few errors while running the program. The error said that, function `inputString` was not defined. I think its some issue with the builtin library. Please look into the issue.

It has being fixed now @pranavbaburaj . If it still doesn't work please create an issue

**Comment by pranavbaburaj** [comment]
Ah sure. I will let you know if it doesn't work.

**Pull request merged**
